[build]
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js","pdfkit"]

# Map /api/* → /.netlify/functions/*
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
